
volumes:
  l2_ipc:

services:
  rise-exec:
    container_name: rise-exec
    image: public.ecr.aws/risechain/risechain-public/rise-exec/replica:sha-4d4a693
    restart: unless-stopped
    deploy:
      ## Resource usage and Limit
      # Depend on your system
      resources:
        limits:
            cpus: 10
            memory: 100g
        reservations:
            cpus: 8
            memory: 80g
    ports:
      - "8545:8545" # rpc
      - "8546:8546" # ws
      - "9001:9001" # metrics
    command:
      - node
      - --chain=/genesis.json
      - --datadir=/db
      - --http
      - --http.api=eth,web3
      - --http.addr=0.0.0.0
      - --http.port=8545
      - --ws
      - --ws.api=eth,web3
      - --ws.addr=0.0.0.0
      - --ws.port=8546
      - --authrpc.jwtsecret=/config/jwt.txt
      - --auth-ipc
      - --auth-ipc.path=/ipc/auth_reth.ipc
      - --metrics=0.0.0.0:9001
      - --txpool.nolocals
      - --txpool.pending_max_count=1000000
      - --txpool.pending_max_size=1000000
      - --txpool.max-account-slots=18446744073709551615
      - --txpool.queued-max-count=2000
      - --rpc-max-connections=4294967295
      - --rpc.gascap=64000000
      - --rpc.eth-proof-window=216000
      - --rpc.proof-permits=3
      - --rpc.max-request-size=4
      - --rpc.max-logs-per-response=5000
      - --rpc.max-blocks-per-filter=5000
      - --prune.sender-recovery.full
    environment:
      - RUST_LOG=info
    volumes:
      - "/mnt/data/l2_data:/db"
      - "l2_ipc:/ipc"
      - "${CHAIN_CONFIG_DIR}/genesis.json:/genesis.json"
      - "./jwt.txt:/config/jwt.txt"

  rise-node:
    container_name: rise-node
    depends_on:
      - rise-exec
    image: public.ecr.aws/risechain/risechain-public/rise-op-node:sha-ae63731
    restart: unless-stopped
    deploy:
      ## Resource usage and Limit
      # Depend on your system
      resources:
        limits:
            cpus: 2.5
            memory: 12g
        reservations:
            cpus: 2
            memory: 12g
    ports:
      - "7545:9545"       # rpc
      - "30003:30003/tcp"   # p2p
      - "7300:7300"       # metrics
    command:
      - op-node
      - --l1=${L1_RPC_URL}
      - --l2=/ipc/auth_reth.ipc
      - --l2.jwt-secret=/config/jwt.txt
      - --rollup.config=/rollup.json
      - --rpc.port=9545
      - --rpc.enable-admin
      - --p2p.priv.path=/config/p2p-node-key.txt
      - --p2p.static=${P2P_STATIC}
      - --p2p.listen.ip=0.0.0.0
      - --p2p.listen.tcp=30003
      - --p2p.static.follow-reorg
      - --metrics.enabled
      - --metrics.addr=0.0.0.0
      - --metrics.port=7300
      - --safedb.path=/db/safedb_data
      - --altda.da-server=${DA_SERVER}
    environment:
      - OP_NODE_L1_EPOCH_POLL_INTERVAL=12s
      - OP_NODE_L1_HTTP_POLL_INTERVAL=6s
      - OP_NODE_L1_RPC_MAX_BATCH_SIZE=30
      - OP_NODE_L1_MAX_CONCURRENCY=30
      - OP_NODE_VERIFIER_L1_CONFS=12
      - OP_NODE_ALTDA_MAX_CONCURRENT_DA_REQUESTS=5
      - OP_NODE_P2P_GOSSIP_TIMESTAMP_THRESHOLD=45m0s
      - OP_NODE_LOG_LEVEL=DEBUG
    volumes:
      - "/mnt/data/safedb_data:/db/safedb_data"
      - "./jwt.txt:/config/jwt.txt"
      - "${CHAIN_CONFIG_DIR}/rollup.json:/rollup.json"
      - "l2_ipc:/ipc"
