global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'op-node'
    static_configs:
      - targets: ['rise-node:7300']
  - job_name: 'execution'
    static_configs: 
      - targets: ['rise-exec:9001']