{
 "title": "rise-node",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "L2",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_node_default_refs_number{layer=\"l2\", type=\"l2_unsafe\"}",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "op_node_default_refs_number{layer=\"l2\", type=\"l2_safe\"}",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "op_node_default_refs_number{layer=\"l2\", type=\"l2_finalized\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "rise-exec",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_node_default_rpc_client_request_duration_seconds_bucket{method=\"engine_forkchoiceUpdatedV3\", le=\"1\"}",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "op_node_default_rpc_client_request_duration_seconds_bucket{le=\"1\", method=\"engine_newPayloadV3\"}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "op_node_default_p2p_peer_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "L1",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_node_default_refs_number{layer=\"l1\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "rise-node",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_node_default_rpc_client_request_duration_seconds_bucket{le=\"1\", method=\"eth_getBlockByHash\"}",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "op_node_default_rpc_client_request_duration_seconds_bucket{le=\"1\", method=\"alchemy_getTransactionReceipts\"}",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "op_node_default_rpc_client_request_duration_seconds_bucket{le=\"1\", method=\"eth_getBlockByNumber\"}",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}